apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-w-jenkins
spec:
  selector:
    matchLabels:
      app: k8s-pipeline
  replicas: 2
  template: 
    metadata:
      labels:
        app: k8s-pipeline
    spec:
      containers: 
        - name: k8s-pipeline
          image: adishrijain/nodejs-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080


---


apiVersion: v1
kind: Service
metadata: 
  name: k8s-service
spec:
  selector:
    app: k8s-pipeline
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort








